project:
  type: website
  output-dir: docs

website:
  #title: "Alexander Ros√©n"
  navbar:
    left:
      - href: index.qmd
        text: "About me"
      - href: Key_skills.qmd
        text: "Key skills"
      - href: CV.qmd
        text: "CV"
      - href: Publications_and_outreach.qmd
        text: "Publications, presentations and outreach"
      - href: Contact.qmd
        text: "Contact information"

format:
  html:
    #theme: Simplex
    theme: [Simplex, clean.scss]
    fontsize: 1.05em
    image-width: 1.2em
    image-shape: round
    css: styles.css
    toc: true



